import Head from "next/head";

export default function GlobalHead({}){

    return(
        <Head>
            <title>RUKTUM</title>
            <meta name="description" content="Generated by me" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    )
}